server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

### MYBATIS ###
mybatis:
  mapper-locations: "classpath:mybatis/mapper/**/**.xml"